version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: flytrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flytrack
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./flytrack.sql:/docker-entrypoint-initdb.d/flytrack.sql

  app:
    build: .
    container_name: flytrack-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flytrack?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql

volumes:
  mysql_data: